(cl:in-package myserial-srv)
(cl:export '(A1-VAL
          A1
          A2-VAL
          A2
          A3-VAL
          A3
          A4-VAL
          A4
          A5-VAL
          A5
          A6-VAL
          A6
          A7-VAL
          A7
          A8-VAL
          A8
          A9-VAL
          A9
          B1-VAL
          B1
          B2-VAL
          B2
          B3-VAL
          B3
          B4-VAL
          B4
          B5-VAL
          B5
          B6-VAL
          B6
          B7-VAL
          B7
          B8-VAL
          B8
          B9-VAL
          B9
))