// Generated by gencpp from file myserial/myserial.msg
// DO NOT EDIT!


#ifndef MYSERIAL_MESSAGE_MYSERIAL_H
#define MYSERIAL_MESSAGE_MYSERIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myserial
{
template <class ContainerAllocator>
struct myserial_
{
  typedef myserial_<ContainerAllocator> Type;

  myserial_()
    : a1(0.0)
    , a2(0.0)
    , a3(0.0)
    , a4(0.0)
    , a5(0.0)
    , a6(0.0)
    , a7(0.0)
    , a8(0.0)
    , a9(0.0)  {
    }
  myserial_(const ContainerAllocator& _alloc)
    : a1(0.0)
    , a2(0.0)
    , a3(0.0)
    , a4(0.0)
    , a5(0.0)
    , a6(0.0)
    , a7(0.0)
    , a8(0.0)
    , a9(0.0)  {
  (void)_alloc;
    }



   typedef float _a1_type;
  _a1_type a1;

   typedef float _a2_type;
  _a2_type a2;

   typedef float _a3_type;
  _a3_type a3;

   typedef float _a4_type;
  _a4_type a4;

   typedef float _a5_type;
  _a5_type a5;

   typedef float _a6_type;
  _a6_type a6;

   typedef float _a7_type;
  _a7_type a7;

   typedef float _a8_type;
  _a8_type a8;

   typedef float _a9_type;
  _a9_type a9;





  typedef boost::shared_ptr< ::myserial::myserial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myserial::myserial_<ContainerAllocator> const> ConstPtr;

}; // struct myserial_

typedef ::myserial::myserial_<std::allocator<void> > myserial;

typedef boost::shared_ptr< ::myserial::myserial > myserialPtr;
typedef boost::shared_ptr< ::myserial::myserial const> myserialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myserial::myserial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myserial::myserial_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace myserial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'myserial': ['/home/ubuntu/catkin_ws/src/myserial/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::myserial::myserial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myserial::myserial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myserial::myserial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myserial::myserial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myserial::myserial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myserial::myserial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myserial::myserial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f27b126aa6a2fa91707e5d51287b08bd";
  }

  static const char* value(const ::myserial::myserial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf27b126aa6a2fa91ULL;
  static const uint64_t static_value2 = 0x707e5d51287b08bdULL;
};

template<class ContainerAllocator>
struct DataType< ::myserial::myserial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myserial/myserial";
  }

  static const char* value(const ::myserial::myserial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myserial::myserial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a1\n\
float32 a2\n\
float32 a3\n\
float32 a4\n\
float32 a5\n\
float32 a6\n\
float32 a7\n\
float32 a8\n\
float32 a9\n\
";
  }

  static const char* value(const ::myserial::myserial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myserial::myserial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a1);
      stream.next(m.a2);
      stream.next(m.a3);
      stream.next(m.a4);
      stream.next(m.a5);
      stream.next(m.a6);
      stream.next(m.a7);
      stream.next(m.a8);
      stream.next(m.a9);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myserial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myserial::myserial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myserial::myserial_<ContainerAllocator>& v)
  {
    s << indent << "a1: ";
    Printer<float>::stream(s, indent + "  ", v.a1);
    s << indent << "a2: ";
    Printer<float>::stream(s, indent + "  ", v.a2);
    s << indent << "a3: ";
    Printer<float>::stream(s, indent + "  ", v.a3);
    s << indent << "a4: ";
    Printer<float>::stream(s, indent + "  ", v.a4);
    s << indent << "a5: ";
    Printer<float>::stream(s, indent + "  ", v.a5);
    s << indent << "a6: ";
    Printer<float>::stream(s, indent + "  ", v.a6);
    s << indent << "a7: ";
    Printer<float>::stream(s, indent + "  ", v.a7);
    s << indent << "a8: ";
    Printer<float>::stream(s, indent + "  ", v.a8);
    s << indent << "a9: ";
    Printer<float>::stream(s, indent + "  ", v.a9);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYSERIAL_MESSAGE_MYSERIAL_H
