// Generated by gencpp from file myserial/myserialsrvRequest.msg
// DO NOT EDIT!


#ifndef MYSERIAL_MESSAGE_MYSERIALSRVREQUEST_H
#define MYSERIAL_MESSAGE_MYSERIALSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myserial
{
template <class ContainerAllocator>
struct myserialsrvRequest_
{
  typedef myserialsrvRequest_<ContainerAllocator> Type;

  myserialsrvRequest_()
    : A1(0.0)
    , A2(0.0)
    , A3(0.0)
    , A4(0.0)
    , A5(0.0)
    , A6(0.0)
    , A7(0.0)
    , A8(0.0)
    , A9(0.0)  {
    }
  myserialsrvRequest_(const ContainerAllocator& _alloc)
    : A1(0.0)
    , A2(0.0)
    , A3(0.0)
    , A4(0.0)
    , A5(0.0)
    , A6(0.0)
    , A7(0.0)
    , A8(0.0)
    , A9(0.0)  {
  (void)_alloc;
    }



   typedef float _A1_type;
  _A1_type A1;

   typedef float _A2_type;
  _A2_type A2;

   typedef float _A3_type;
  _A3_type A3;

   typedef float _A4_type;
  _A4_type A4;

   typedef float _A5_type;
  _A5_type A5;

   typedef float _A6_type;
  _A6_type A6;

   typedef float _A7_type;
  _A7_type A7;

   typedef float _A8_type;
  _A8_type A8;

   typedef float _A9_type;
  _A9_type A9;





  typedef boost::shared_ptr< ::myserial::myserialsrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myserial::myserialsrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct myserialsrvRequest_

typedef ::myserial::myserialsrvRequest_<std::allocator<void> > myserialsrvRequest;

typedef boost::shared_ptr< ::myserial::myserialsrvRequest > myserialsrvRequestPtr;
typedef boost::shared_ptr< ::myserial::myserialsrvRequest const> myserialsrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myserial::myserialsrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myserial::myserialsrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace myserial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'myserial': ['/home/ubuntu/catkin_ws/src/myserial/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::myserial::myserialsrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myserial::myserialsrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myserial::myserialsrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myserial::myserialsrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myserial::myserialsrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myserial::myserialsrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myserial::myserialsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e8ab01964adad3e006b48c1a37034a8";
  }

  static const char* value(const ::myserial::myserialsrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e8ab01964adad3eULL;
  static const uint64_t static_value2 = 0x006b48c1a37034a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::myserial::myserialsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myserial/myserialsrvRequest";
  }

  static const char* value(const ::myserial::myserialsrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myserial::myserialsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 A1\n\
float32 A2\n\
float32 A3\n\
float32 A4\n\
float32 A5\n\
float32 A6\n\
float32 A7\n\
float32 A8\n\
float32 A9\n\
";
  }

  static const char* value(const ::myserial::myserialsrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myserial::myserialsrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A1);
      stream.next(m.A2);
      stream.next(m.A3);
      stream.next(m.A4);
      stream.next(m.A5);
      stream.next(m.A6);
      stream.next(m.A7);
      stream.next(m.A8);
      stream.next(m.A9);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myserialsrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myserial::myserialsrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myserial::myserialsrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "A1: ";
    Printer<float>::stream(s, indent + "  ", v.A1);
    s << indent << "A2: ";
    Printer<float>::stream(s, indent + "  ", v.A2);
    s << indent << "A3: ";
    Printer<float>::stream(s, indent + "  ", v.A3);
    s << indent << "A4: ";
    Printer<float>::stream(s, indent + "  ", v.A4);
    s << indent << "A5: ";
    Printer<float>::stream(s, indent + "  ", v.A5);
    s << indent << "A6: ";
    Printer<float>::stream(s, indent + "  ", v.A6);
    s << indent << "A7: ";
    Printer<float>::stream(s, indent + "  ", v.A7);
    s << indent << "A8: ";
    Printer<float>::stream(s, indent + "  ", v.A8);
    s << indent << "A9: ";
    Printer<float>::stream(s, indent + "  ", v.A9);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYSERIAL_MESSAGE_MYSERIALSRVREQUEST_H
