// Generated by gencpp from file myserial/myserialsrv.msg
// DO NOT EDIT!


#ifndef MYSERIAL_MESSAGE_MYSERIALSRV_H
#define MYSERIAL_MESSAGE_MYSERIALSRV_H

#include <ros/service_traits.h>


#include <myserial/myserialsrvRequest.h>
#include <myserial/myserialsrvResponse.h>


namespace myserial
{

struct myserialsrv
{

typedef myserialsrvRequest Request;
typedef myserialsrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct myserialsrv
} // namespace myserial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myserial::myserialsrv > {
  static const char* value()
  {
    return "8201a68440ff5daa0bba491b406dad47";
  }

  static const char* value(const ::myserial::myserialsrv&) { return value(); }
};

template<>
struct DataType< ::myserial::myserialsrv > {
  static const char* value()
  {
    return "myserial/myserialsrv";
  }

  static const char* value(const ::myserial::myserialsrv&) { return value(); }
};


// service_traits::MD5Sum< ::myserial::myserialsrvRequest> should match 
// service_traits::MD5Sum< ::myserial::myserialsrv > 
template<>
struct MD5Sum< ::myserial::myserialsrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myserial::myserialsrv >::value();
  }
  static const char* value(const ::myserial::myserialsrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myserial::myserialsrvRequest> should match 
// service_traits::DataType< ::myserial::myserialsrv > 
template<>
struct DataType< ::myserial::myserialsrvRequest>
{
  static const char* value()
  {
    return DataType< ::myserial::myserialsrv >::value();
  }
  static const char* value(const ::myserial::myserialsrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myserial::myserialsrvResponse> should match 
// service_traits::MD5Sum< ::myserial::myserialsrv > 
template<>
struct MD5Sum< ::myserial::myserialsrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myserial::myserialsrv >::value();
  }
  static const char* value(const ::myserial::myserialsrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myserial::myserialsrvResponse> should match 
// service_traits::DataType< ::myserial::myserialsrv > 
template<>
struct DataType< ::myserial::myserialsrvResponse>
{
  static const char* value()
  {
    return DataType< ::myserial::myserialsrv >::value();
  }
  static const char* value(const ::myserial::myserialsrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYSERIAL_MESSAGE_MYSERIALSRV_H
