# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from myserial/myserial.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class myserial(genpy.Message):
  _md5sum = "f27b126aa6a2fa91707e5d51287b08bd"
  _type = "myserial/myserial"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 a1
float32 a2
float32 a3
float32 a4
float32 a5
float32 a6
float32 a7
float32 a8
float32 a9
"""
  __slots__ = ['a1','a2','a3','a4','a5','a6','a7','a8','a9']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       a1,a2,a3,a4,a5,a6,a7,a8,a9

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(myserial, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.a1 is None:
        self.a1 = 0.
      if self.a2 is None:
        self.a2 = 0.
      if self.a3 is None:
        self.a3 = 0.
      if self.a4 is None:
        self.a4 = 0.
      if self.a5 is None:
        self.a5 = 0.
      if self.a6 is None:
        self.a6 = 0.
      if self.a7 is None:
        self.a7 = 0.
      if self.a8 is None:
        self.a8 = 0.
      if self.a9 is None:
        self.a9 = 0.
    else:
      self.a1 = 0.
      self.a2 = 0.
      self.a3 = 0.
      self.a4 = 0.
      self.a5 = 0.
      self.a6 = 0.
      self.a7 = 0.
      self.a8 = 0.
      self.a9 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9f().pack(_x.a1, _x.a2, _x.a3, _x.a4, _x.a5, _x.a6, _x.a7, _x.a8, _x.a9))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.a1, _x.a2, _x.a3, _x.a4, _x.a5, _x.a6, _x.a7, _x.a8, _x.a9,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9f().pack(_x.a1, _x.a2, _x.a3, _x.a4, _x.a5, _x.a6, _x.a7, _x.a8, _x.a9))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.a1, _x.a2, _x.a3, _x.a4, _x.a5, _x.a6, _x.a7, _x.a8, _x.a9,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9f = None
def _get_struct_9f():
    global _struct_9f
    if _struct_9f is None:
        _struct_9f = struct.Struct("<9f")
    return _struct_9f
